services:
  tinyproxy-client:
    image: tinyproxy
    build: .
    container_name: tinyproxy-client
    restart: unless-stopped
    ports:
      - 8888:8888
    networks: 
      - tinyproxy-network

networks: 
  tinyproxy-network:
    name: tinyproxy-network
    driver: bridge
